debug: true
spring:
  profiles:
  active: dev

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql=true: true
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: 'create-drop'
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        show_sql=true:h2:
    console:
      enabled: true