---
server:
  port: 8080
spring:
  profiles: local

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql=true: true
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

    properties:
      hibernate:
        show_sql=true:h2:
    console:
      enabled: true

---
server:
  port: 8080
spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
