jwtSecretKey: cultureLand  #실행시에 Argument로 주입
spring:
  application:
    name: '@artifactId@'
cloud:
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    bucket: cultureland
---
server:
  port: 8080

spring:
  profiles: local

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql=true: true
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

debug: true
---
server:
  port: 8080

spring:
  profiles: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root}
    initialization-mode: always # 하면 안됨 prod일 땐
---
spring:
  profiles: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_PROD_USER_NAME}
    password: ${DB_PROD_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
