debug: false
jwtSecretKey: cultureLand  #실행시에 Argument로 주입
---
server:
  port: 8080
spring:
  profiles:
    active: local

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql=true: true
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: 'create-drop'
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
      path: /h2-console

    properties:
      hibernate:
        show_sql=true:h2:
---
spring:
  profiles: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

---
